/**
 * Organizze API
 * The Organizze API enables communication with your Organizze account. This document explains how Organizze works, the involved objects, and how communication can be achieved. This is the first version of the API, still in beta, and some changes and improvements will be implemented in the future. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreditCard {
    'id'?: number;
    'name'?: string;
    'description'?: string;
    'cardNetwork'?: string;
    'closingDay'?: number;
    'dueDay'?: number;
    'limitCents'?: number;
    'kind'?: string;
    'archived'?: boolean;
    '_default'?: boolean;
    'createdAt'?: Date;
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "cardNetwork",
            "baseName": "card_network",
            "type": "string",
            "format": ""
        },
        {
            "name": "closingDay",
            "baseName": "closing_day",
            "type": "number",
            "format": ""
        },
        {
            "name": "dueDay",
            "baseName": "due_day",
            "type": "number",
            "format": ""
        },
        {
            "name": "limitCents",
            "baseName": "limit_cents",
            "type": "number",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string",
            "format": ""
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return CreditCard.attributeTypeMap;
    }

    public constructor() {
    }
}

